spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./target/h2db/db/example;DB_CLOSE_DELAY=-1
      username: access
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

camunda:
  bpm:
    admin-user:
      password: demo
      id: demo
      first-name: Demo
      last-name: Demo
      email: info@mail.com